version: "3.8"

services:
  api:
    container_name: apartmentrentalapi
    restart: unless-stopped
    image: aquaprogit/apartmentrentailapi:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=ApartmentRental;User Id=sa;Password=S3cur3P@ssW0rd!;TrustServerCertificate=True;MultipleActiveResultSets=true
    networks:
      - apartmentrental-network

  db:
    container_name: apartmentrentaldb
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    restart: unless-stopped
    ports:
      - "1435:1433"
    environment:
      - SA_PASSWORD=S3cur3P@ssW0rd!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - apartmentrental-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "S3cur3P@ssW0rd!" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  apartmentrental-network:
    driver: bridge

volumes:
  sqlserver-data:
